### ISSUE TITLE
newFeature-2: multiple acceptance of operation in array

### ISSUE THREAD

**Issue by mdwajid095** [mdwajid095/kafka-acl-operator#2]
update operator to reconcile ACls with cluster with array of operation.

```
apiVersion: emp.namespaced.com/v1alpha1
kind: KafkaACL
metadata:
  name: my-kafka-acl-ns-v1
  namespace: confluent
spec:
  principal: "User:acl-test"
  resourceType: "TOPIC"
  resourceName:
    - "tef.de.topas.BarringEvents-MM-v1"
    - "tef.de.testing-v1"
    - "tef.de.testing-v2"
  operation: ["READ"]
  permissionType: "ALLOW"
  patternType: "LITERAL"
```
